include_recipe 'build-essential::default'
include_recipe 'python::pip'
include_recipe 'python::virtualenv'

package 'postgresql-devel'
package 'python-devel'
package 'openssl-devel'
package 'httpd-tools'
package 'pcre'
package 'pcre-devel'
package 'epel-release'
package 'nodejs'
package 'npm'
package 'nginx'
package 'vim'
package 'git'
